# This workflow will build and push a node.js to a dev branch.
# Linting, Code checking, Testing and JSDoc generation are run for pushes to a dev branch
on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      run: |
        # run tests to ensure code is functional
        npm install
    - name: jest test
      run: npm test
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Super-Linter
      uses: github/super-linter@v4.8.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  jsdoc-generator:
    runs-on: ubuntu-latest
    steps:
    - name: JSDoc Action
      uses: andstor/jsdoc-action@v1.2.0
      with:
        source_dir: ./source
        recurse: true
        output_dir: ./out
