# This is a basic workflow to help you get started with Actions

name: spatch

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-deploy-publish:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://npm.pkg.github.com/
        scope: '@cse110-fa21-group18'
    - name: Deploy
      run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
    - name: npm install, build, and test
      run: |
        npm install
        npm build
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Super-Linter
      uses: github/super-linter@v4.8.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  jsdoc-generator:
    runs-on: ubuntu-latest
    steps:
    - name: JSDoc Action
      uses: andstor/jsdoc-action@v1.2.0
  code-coverage-report:
    runs-on: ubuntu-latest
    steps:
    - name: Code Coverage Report
      uses: romeovs/lcov-reporter-action@v0.2.11
      with:
        lcov-file: ./coverage/lcov.info
  
